import { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { liveStreamService, LiveStream, GIFT_LIST, GiftType } from '../services/liveStreamService';
import { getUserInfo } from '../utils/userUtils';

interface Message {
    id: string;
    user: string;
    text: string;
    isStreamer?: boolean;
    isGift?: boolean;
    giftIcon?: string;
    giftName?: string;
    giftCount?: number;
}

interface FloatingHeart {
    id: number;
    left: number;
    animationDuration: number;
}

interface FloatingGift {
    id: number;
    icon: string;
    name: string;
    user: string;
}

const formatViewers = (num: number): string => {
    if (num >= 10000) return (num / 10000).toFixed(1) + 'w';
    if (num >= 1000) return (num / 1000).toFixed(1) + 'k';
    return String(num);
};

const LiveRoom = () => {
    const navigate = useNavigate();
    const { id } = useParams<{ id: string }>();
    const [stream, setStream] = useState<LiveStream | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [liked, setLiked] = useState(false);
    const [isRefreshing, setIsRefreshing] = useState(false);
    const [isFollowed, setIsFollowed] = useState(false);
    const [inputValue, setInputValue] = useState('');
    const [floatingHearts, setFloatingHearts] = useState<FloatingHeart[]>([]);
    const [floatingGifts, setFloatingGifts] = useState<FloatingGift[]>([]);
    const [showGiftPanel, setShowGiftPanel] = useState(false);
    const [messages, setMessages] = useState<Message[]>([]);
    const [isGeneratingComments, setIsGeneratingComments] = useState(false);
    const userInfo = getUserInfo();

    const chatContainerRef = useRef<HTMLDivElement>(null);
    const heartIdCounter = useRef(0);
    const giftIdCounter = useRef(0);
    const commentIntervalRef = useRef<NodeJS.Timeout | null>(null);

    // Load stream data
    useEffect(() => {
        const loadStream = async () => {
            if (!id) return;
            setIsLoading(true);
            try {
                await liveStreamService.initialize();
                const streamData = liveStreamService.getStream(id);
                if (streamData) {
                    setStream(streamData);
                    liveStreamService.addViewer(id);
                    // Load initial comments
                    loadInitialComments();
                }
            } catch (e) {
                console.error('Load stream failed:', e);
            } finally {
                setIsLoading(false);
            }
        };
        loadStream();

        return () => {
            if (commentIntervalRef.current) {
                clearInterval(commentIntervalRef.current);
            }
        };
    }, [id]);

    // Load initial comments from stream data (already generated by AI)
    const loadInitialComments = async () => {
        if (!id) return;
        
        // 先加载已生成的初始弹幕
        const streamData = liveStreamService.getStream(id);
        if (streamData?.comments?.length) {
            const existingMsgs: Message[] = streamData.comments.map(c => ({
                id: c.id,
                user: c.userName,
                text: c.content,
                isStreamer: c.userId === streamData.streamerId
            }));
            setMessages(existingMsgs);
        }
        
        // 定时生成新弹幕
        commentIntervalRef.current = setInterval(async () => {
            setIsGeneratingComments(true);
            try {
                const newComments = await liveStreamService.generateComments(id, 2);
                newComments.forEach(c => {
                    setMessages(prev => [...prev.slice(-50), {
                        id: c.id,
                        user: c.userName,
                        text: c.content
                    }]);
                });
            } catch (e) {
                console.error('Generate comments failed:', e);
            } finally {
                setIsGeneratingComments(false);
            }
        }, 15000); // Every 15 seconds
    };

    
    // Scroll to bottom on new message
    useEffect(() => {
        if (chatContainerRef.current) {
            chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
        }
    }, [messages]);

    // 刷新直播内容
    const handleRefresh = async () => {
        if (!id || isRefreshing) return;
        setIsRefreshing(true);
        try {
            // 强制刷新
            await liveStreamService.initialize(true);
            const streamData = liveStreamService.getStream(id);
            if (streamData) {
                setStream(streamData);
                // 重新加载弹幕
                setMessages([]);
                loadInitialComments();
            }
        } catch (e) {
            console.error('刷新失败:', e);
        } finally {
            setIsRefreshing(false);
        }
    };

    const handleLike = (e: React.MouseEvent) => {
        e.stopPropagation();
        setLiked(!liked);
        if (id) liveStreamService.addLike(id);
        triggerHeartAnimation();
    };

    const triggerHeartAnimation = () => {
        const heartId = heartIdCounter.current++;
        const newHeart: FloatingHeart = {
            id: heartId,
            left: 50 + (Math.random() * 40 - 20),
            animationDuration: 1.5 + Math.random(),
        };
        setFloatingHearts(prev => [...prev, newHeart]);
        setTimeout(() => {
            setFloatingHearts(prev => prev.filter(h => h.id !== heartId));
        }, 2500);
    };

    // Send gift
    const handleSendGift = async (gift: GiftType) => {
        if (!id || !stream) return;
        
        const userName = userInfo.nickname || 'Me';
        
        // Add gift message
        const giftMsg: Message = {
            id: `gift_${Date.now()}`,
            user: userName,
            text: `sent ${gift.name}`,
            isGift: true,
            giftIcon: gift.icon,
            giftName: gift.name,
            giftCount: 1
        };
        setMessages(prev => [...prev, giftMsg]);
        
        // Floating gift animation
        const giftId = giftIdCounter.current++;
        setFloatingGifts(prev => [...prev, {
            id: giftId,
            icon: gift.icon,
            name: gift.name,
            user: userName
        }]);
        setTimeout(() => {
            setFloatingGifts(prev => prev.filter(g => g.id !== giftId));
        }, 3000);
        
        // Save gift
        liveStreamService.sendGift(id, 'user', userName, gift, 1);
        
        // Streamer reply
        setTimeout(async () => {
            const reply = await liveStreamService.generateStreamerReply(id, `${userName} gave ${gift.name}`);
            setMessages(prev => [...prev, {
                id: `streamer_${Date.now()}`,
                user: stream.streamerName,
                text: reply,
                isStreamer: true
            }]);
        }, 1500);
        
        setShowGiftPanel(false);
    };

    const handleSendMessage = async (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter' && inputValue.trim() && id && stream) {
            const userName = userInfo.nickname || 'Me';
            const msgText = inputValue.trim();
            
            const newMessage: Message = {
                id: `msg_${Date.now()}`,
                user: userName,
                text: msgText
            };
            setMessages(prev => [...prev, newMessage]);
            setInputValue('');
            
            // Streamer AI reply
            setTimeout(async () => {
                const reply = await liveStreamService.generateStreamerReply(id, msgText);
                setMessages(prev => [...prev, {
                    id: `streamer_${Date.now()}`,
                    user: stream.streamerName,
                    text: reply,
                    isStreamer: true
                }]);
            }, 2000);
        }
    };

    const handleFollow = (e: React.MouseEvent) => {
        e.stopPropagation();
        setIsFollowed(!isFollowed);
    };

    if (isLoading) {
        return (
            <div className="h-full w-full flex items-center justify-center bg-black">
                <div className="w-12 h-12 border-2 border-white/20 border-t-white/80 rounded-full animate-spin" />
            </div>
        );
    }

    if (!stream) {
        return (
            <div className="h-full w-full flex flex-col items-center justify-center bg-black text-white">
                <p className="text-white/60 mb-4">Live stream not found</p>
                <button onClick={() => navigate(-1)} className="px-4 py-2 bg-white/10 rounded-full text-sm">Go Back</button>
            </div>
        );
    }

    return (
        <div className="h-full w-full relative bg-black text-white font-serif overflow-hidden">
            {/* Background with stream color */}
            <div className="absolute inset-0 z-0">
                <div className={`w-full h-full bg-gradient-to-br ${stream.color} animate-pulse-slow`}>
                    <div className="absolute inset-0 opacity-30 mix-blend-overlay bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />
                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-500/20 rounded-full blur-[100px]" />
                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/20 rounded-full blur-[100px]" />
                </div>
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                    <span className="text-white/10 text-9xl font-serif tracking-widest opacity-20">LIVE</span>
                </div>
            </div>

            {/* Floating Hearts */}
            <div className="absolute bottom-20 right-4 w-20 h-64 pointer-events-none z-10 overflow-hidden">
                {floatingHearts.map(heart => (
                    <div
                        key={heart.id}
                        className="absolute bottom-0 text-red-500 animate-float-up opacity-0"
                        style={{ left: `${heart.left}%`, animationDuration: `${heart.animationDuration}s` }}
                    >
                        <svg className="w-6 h-6 fill-current" viewBox="0 0 24 24">
                            <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                        </svg>
                    </div>
                ))}
            </div>

            {/* Floating Gifts */}
            <div className="absolute top-1/3 left-1/2 -translate-x-1/2 pointer-events-none z-30">
                {floatingGifts.map(gift => (
                    <div key={gift.id} className="animate-gift-float text-center">
                        <div className="text-6xl mb-2 animate-bounce">{gift.icon}</div>
                        <div className="bg-gradient-to-r from-pink-500 to-purple-500 text-white px-4 py-1 rounded-full text-sm">
                            {gift.user} sent {gift.name}
                        </div>
                    </div>
                ))}
            </div>

            {/* Top Bar - Streamer Info */}
            <div className="absolute top-0 left-0 w-full p-4 pt-12 flex items-center justify-between z-20">
                <div className="flex items-center bg-black/20 backdrop-blur-md rounded-full pl-1 pr-4 py-1 border border-white/10">
                    {stream.streamerAvatar ? (
                        <img src={stream.streamerAvatar} alt="" className="w-8 h-8 rounded-full mr-3 object-cover" />
                    ) : (
                        <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-amber-200 to-amber-500 mr-3" />
                    )}
                    <div className="flex flex-col">
                        <span className="text-xs font-medium tracking-wide">{stream.streamerName}</span>
                        <span className="text-[10px] text-white/60">{formatViewers(stream.viewers)} watching</span>
                    </div>
                    <button
                        onClick={handleFollow}
                        className={`ml-4 px-3 py-0.5 rounded-full text-[10px] transition-all duration-300 ${isFollowed ? 'bg-white/10 text-white/60' : 'bg-red-500/80 text-white hover:bg-red-600'}`}
                    >
                        {isFollowed ? 'Followed' : 'Follow'}
                    </button>
                </div>

                <div className="flex items-center space-x-2">
                    {/* 刷新按钮 */}
                    <button
                        onClick={handleRefresh}
                        disabled={isRefreshing}
                        className="w-8 h-8 flex items-center justify-center rounded-full bg-black/20 backdrop-blur-md border border-white/10 hover:bg-white/20 transition-colors"
                    >
                        <svg className={`w-5 h-5 ${isRefreshing ? 'animate-spin' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                        </svg>
                    </button>
                    <button
                        onClick={() => navigate(-1)}
                        className="w-8 h-8 flex items-center justify-center rounded-full bg-black/20 backdrop-blur-md border border-white/10 hover:bg-white/20 transition-colors"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
            </div>

            {/* Stream Title */}
            <div className="absolute top-24 left-4 right-4 z-20">
                <div className="bg-black/20 backdrop-blur-md rounded-xl p-3 border border-white/10">
                    <div className="flex items-center gap-2 mb-1">
                        <span className="px-2 py-0.5 bg-red-500/80 rounded text-[10px]">LIVE</span>
                        <span className="text-[10px] text-white/60">{stream.category}</span>
                    </div>
                    <h2 className="text-sm font-medium">{stream.title}</h2>
                    {stream.description && <p className="text-xs text-white/50 mt-1">{stream.description}</p>}
                </div>
            </div>

            {/* Bottom Area - 始终显示，不随控制隐藏 */}
            <div
                className="absolute bottom-0 left-0 w-full z-20 bg-gradient-to-t from-black/90 via-black/50 to-transparent pt-20 pb-8 px-4"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Chat Messages */}
                <div ref={chatContainerRef} className="w-3/4 max-h-48 overflow-y-auto mb-6 space-y-2 scrollbar-hide">
                    {messages.map((msg) => (
                        <div key={msg.id} className={`flex items-start space-x-2 animate-fade-in-up ${msg.isStreamer ? 'bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-lg px-2 py-1 -mx-2' : ''}`}>
                            {msg.isGift ? (
                                <span className="text-yellow-400 text-sm">
                                    <span className="text-white/80 font-medium">{msg.user}</span> sent {msg.giftIcon} {msg.giftName}
                                </span>
                            ) : (
                                <>
                                    <span className={`text-sm font-medium whitespace-nowrap ${msg.isStreamer ? 'text-pink-400' : 'text-white/60'}`}>
                                        {msg.isStreamer && '🎤 '}{msg.user}:
                                    </span>
                                    <span className="text-white/90 text-sm font-light leading-relaxed">{msg.text}</span>
                                </>
                            )}
                        </div>
                    ))}
                    {isGeneratingComments && (
                        <div className="text-white/30 text-xs">Loading comments...</div>
                    )}
                </div>

                {/* Action Bar */}
                <div className="flex items-center justify-between">
                    <div className="flex-1 mr-4">
                        <input
                            type="text"
                            value={inputValue}
                            onChange={(e) => setInputValue(e.target.value)}
                            onKeyDown={handleSendMessage}
                            placeholder="Say something..."
                            className="w-full h-10 bg-black/20 backdrop-blur-md border border-white/10 rounded-full px-4 text-white text-sm font-light placeholder-white/40 focus:outline-none focus:bg-black/40 focus:border-white/20 transition-all"
                        />
                    </div>

                    <div className="flex items-center space-x-3">
                        {/* Share */}
                        <button className="p-2 rounded-full bg-white/5 backdrop-blur-sm border border-white/10 hover:bg-white/10 transition-all active:scale-95">
                            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                            </svg>
                        </button>
                        
                        {/* Gift Button */}
                        <button 
                            onClick={() => setShowGiftPanel(true)}
                            className="p-2 rounded-full bg-gradient-to-r from-yellow-500/20 to-orange-500/20 backdrop-blur-sm border border-yellow-500/30 hover:from-yellow-500/30 hover:to-orange-500/30 transition-all active:scale-95"
                        >
                            <svg className="w-6 h-6 text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M12 8v13m0-13V6a2 2 0 112 2h-2zm0 0V5.5A2.5 2.5 0 109.5 8H12zm-7 4h14M5 12a2 2 0 110-4h14a2 2 0 110 4M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7" />
                            </svg>
                        </button>
                        
                        {/* Like */}
                        <button
                            onClick={handleLike}
                            className={`p-2 rounded-full backdrop-blur-sm border transition-all duration-300 active:scale-90 ${liked ? 'bg-red-500/20 border-red-500/50 text-red-500' : 'bg-white/5 border-white/10 text-white hover:bg-white/10'}`}
                        >
                            <svg className={`w-6 h-6 ${liked ? 'fill-current' : 'fill-none'}`} stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>

            {/* Gift Panel */}
            {showGiftPanel && (
                <div className="fixed inset-0 z-50 flex items-end justify-center" onClick={() => setShowGiftPanel(false)}>
                    <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                    <div 
                        className="relative w-full max-w-md bg-[#1a1a1a] rounded-t-3xl p-6 pb-10 animate-slide-up"
                        onClick={e => e.stopPropagation()}
                    >
                        <div className="w-12 h-1 bg-white/20 rounded-full mx-auto mb-6" />
                        <h3 className="text-lg font-medium text-white mb-6 text-center tracking-wider">Send Gift</h3>
                        
                        <div className="grid grid-cols-4 gap-4">
                            {GIFT_LIST.map(gift => (
                                <button
                                    key={gift.id}
                                    onClick={() => handleSendGift(gift)}
                                    className="flex flex-col items-center p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-all active:scale-95"
                                >
                                    <span className="text-3xl mb-2">{gift.icon}</span>
                                    <span className="text-xs text-white/80">{gift.name}</span>
                                    <span className="text-[10px] text-yellow-400">{gift.price} coins</span>
                                </button>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default LiveRoom;
